pub mod Max_Consecutive_Ones_III_1004;
pub mod Maximum_Average_Subarray_I_43;
pub mod Maximum_Number_of_Vowels_in_a_Substring_of_Given_Length_1456;
pub mod Longest_Subarray_of_1_s_After_Deleting_One_Element_1493;
